name: Build with Rollup 2.53.2

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Build
        run: cd ./2.53.2 && npm ci && npm run build
